### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by yondu22** [alphacep/kaldi-android-demo#1]
Waiting patiently for your excellent work

**Comment by nanaghartey** [comment]
This is gold! Thanks @nshmyrev . However, although I was able to run on my device, the accuracy was poor. I kept getting wrong results. Also can we use different models like the aspire model with this?

**Comment by nshmyrev** [comment]
Thank you, colleagues. On accuracy, the model is not optimized yet, very small model would work (10-20 words, small nnet) but large model like aspire not yet, it will require some mobile device optimization. Stay tuned.

**Comment by yondu22** [comment]
@nshmyrev would it be possible for you to open source your jni non-compilled code, also some guide on how you did it?

**Comment by nshmyrev** [comment]
@yondu22 everything is open, https://github.com/kaldi-android contains the project to build aar. The kaldi libraries are compiled with https://github.com/jcsilva/docker-kaldi-android with minor tweaks which I will be merging into kaldi-android too.

**Comment by yondu22** [comment]
thank you, I just saw that repo. Your work is awesome and gold as nana says. If you add wake word, and improve the tts serving capabilities, your git will be a one stop voice asr house ha
