### ISSUE TITLE
The demo doesn't work with other model

### ISSUE THREAD

**Issue by huynguyen82** [alphacep/kaldi-android-demo#11]
Hi Nickolay,
I imported this project, built the apk file and run it on a Pie Android device. Everything was fine with the default kaldi model included in this respo. I further replaced this model by my own developed model (for Vietnamese), rebuilt the apk file and run on the same device. After the demo initialized if i touch  "Recognize File"  or "Recognize Microphone" button the demo will disappear (like core dump or something else). My model was trained using CNN+TDNN config with Kaldi version-5.5, the total size at final is 100M. So do you have any suggestion or idea about this issue?

**Comment by nshmyrev** [comment]
Hi.

Please check logcat output, it might contain too much details.

100M is a bit on a large side, try to train model with less parameters, maybe a bit less accurate, there is a tradeoff between size and accuracy.

Also, make sure you created proper HCLr and Gr fsts with lookahead branch.

**Comment by huynguyen82** [comment]
Thanks Nickolay,
- "_Please check logcat output, it might contain some additional details_": The demo just disappeared without any log or bug.
- "_100M is a bit on a large side, try to train model with less parameters, maybe a bit less accurate, there is a tradeoff between size and accuracy._": I am now trying to train other model with smaller size. But the question is that how much size should be to be suitable. Is that should be less than 50M?
- "_Also, make sure you created proper HCLr and Gr fsts with lookahead branch._": I created HCLr and Gr fsts with lookahead branch.

Do you think that my CNN-TDNN model has some components which are not supported in Kaldi V5.2
My main componets as following: idct-layer, linear-component, batchnorm-component, combine-feature-maps-layer, conv-relu-batchnorm-layer, tdnnf-layer, prefinal-layer, output-layer

**Comment by nshmyrev** [comment]
> "Please check logcat output, it might contain some additional details": The demo just disappeared without any log or bug.

There should be some messages. Please check again. You can get full logcat with `adb logcat`

.> But the question is that how much size should be to be suitable. Is that should be less than 50M?

The current models are about 13Mb, mini librispeech with dimension 768 per layer should work. The RT ratio on the desktop should be less than 0.1xRT, then it will run realtime on the phone. We will optimize and compress models later, for now you can start with very tiny models.

> My main componets as following: idct-layer, linear-component, batchnorm-component, combine-feature-maps-layer, conv-relu-batchnorm-layer, tdnnf-layer, prefinal-layer, output-layer

I don't think it is a problem, logcat should show.

**Comment by huynguyen82** [comment]
Hi Nickolay,
The only line i got from logcat was: 
2019-12-11 16:38:54.979 8172-8723/org.kaldi.demo A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 8723 (AsyncTask #2), pid 8172 (org.kaldi.demo)
I also rechecked kaldi versions, it seems that the TDNN-F is supported from Version 5.4, but the included aar was built with Kaldi version 5.2. I am also trying to rebuild aar  (https://github.com/alphacep/kaldi-android) with the last version of Kaldi but there are still some bugs

**Comment by nshmyrev** [comment]
There must be earlier lines. At least where it unpacks models.

> included aar was built with Kaldi version 5.2

Not true, aar is built with latest kaldi. All released models are tdnn-f.

**Comment by huynguyen82** [comment]
[logcat.txt](https://github.com/alphacep/kaldi-android-demo/files/3954741/logcat.txt)
The attached file is the logcat that i got. It seems that the issue relates to the size of model?

**Comment by nshmyrev** [comment]
Do you see extra lines in the logcat now or still nothing?

**Comment by nshmyrev** [comment]
I would first try with the smaller size.

**Comment by huynguyen82** [comment]
Still nothing, 

> I would first try with the smaller size.

Yes, i am trying retrain my model with small size. This the only choice for now that i can do

**Comment by huynguyen82** [comment]
I still got the same problem with smaller model (14M). I traced back and found that the crashing happens at lines 130, 254 in KaldiActivity.java
I uploaded my demo model at: https://drive.google.com/file/d/1CGpALf2Gp-s-waPLBq6dbI_Dfk9NOAjz/view?usp=sharing
Could you please help me to test it.

**Comment by nshmyrev** [comment]
I see your Gr.fst is standard fst, can you try with arpa fst created with mkgraph_lookahead_arpa? It doesn't handle standard fsts automatically yet.

**Comment by huynguyen82** [comment]
Thank you a lot,
You are right, my model worked with with mkgraph_lookahead_arpa!
