### ISSUE TITLE
Dummy instructions on own model training

### ISSUE THREAD

**Issue by gklasen** [alphacep/kaldi-android-demo#17]
I found...

> "If you want to update the grammar or the acoustic model, check the script mkgraph_lookahead_arpa.sh from lookahead branch at our kaldi fork or from submitted pull request. Hopefully that pull request will be merged soon and graph can be compiled with kaldi master."

... but i am not getting that properly. Are there some easy dummy instructions how to train own ASR models and attach them to the android app? I would be willing to add german language if i figure out how to train.

**Comment by nshmyrev** [comment]
The overall plan is like this

1. You train kaldi model with small number of parameters so that the model size is about 10-15Mb, you can probably follow https://github.com/uhh-lt/kaldi-tuda-de for German

2. You compile the graph with mkgraph_lookahead script.

3. You put the files into the assets folder and run the demo

There are also pretrained models here https://goofy.zamia.org/asr/, you can use tdnn-250 version as is without training, you just need to compile the graph.

We will do it ourselves soon probably.

**Comment by gklasen** [comment]
Thank you!

**Comment by nshmyrev** [comment]
@gklasen I have just uploaded

https://github.com/alphacep/kaldi-android-demo/releases/download/2020-01/alphacep-model-android-de-zamia-0.3.tar.gz

**Comment by gklasen** [comment]
Wow, thanks, nice!

Can you confirm the demo app running if you replace the current model by "alphacep-model-android-en-us-0.3.tar.gz"?

**Comment by nshmyrev** [comment]
Should be, just don't forget to delete old files

**Comment by gklasen** [comment]
It seems the AAR is searching for "words.txt" which no longer is part of the v0.3 models

```
V/KaldiDemo: Computing derived variables for iVector extractor
V/KaldiDemo: Done.
V/KaldiDemo: Removed 1 orphan nodes.
V/KaldiDemo: Removing 2 orphan components.
V/KaldiDemo: Added 1 components, removed 2
V/KaldiDemo: Spent 0.333249 seconds in looped compilation.
V/KaldiDemo: Could not read symbol table from file /storage/emulated/0/Android/data/eu.comprise.sampleapp/files/sync/model-android/words.txt
```

**Comment by nshmyrev** [comment]
You probably didn't update aar from last commit 83b23cfc34dde4b688fbfff7566a460bc9b56455

**Comment by gklasen** [comment]
I thought i did. I took the aar from aar-folder within this project, updated 5 days ago. But i try to build one @ vosk. I still have an issue there (gradle build => Task :kaldi FAILED), but lets see.

**Comment by gklasen** [comment]
Would be great if you could update this app running with 0.3 until i get vosk running

**Comment by nshmyrev** [comment]
@gklasen I have just verified and it works fine with German and English models. Models work as is, you just unpack them. `words.txt` is not required from latest commit but please make sure you deleted all the other files in the project and on the phone sdcard, maybe something remains there.

@erksch should be able get this running too.
