### ISSUE TITLE
语音模型

### ISSUE THREAD

**Issue by czqhubu** [alphacep/kaldi-android-demo#2]
请问支持中文吗？能否直接使用cvte的中文语音模型？

**Comment by nshmyrev** [comment]
CVTE模型太大，必须训练一个特殊模型，减小尺寸。

我先是在学习英语模型，接下来我们可以训练中文。

**Comment by czqhubu** [comment]
嗯，我是看你的模型word里面没有中文，等待楼主的中文模型测试结果

**Comment by nshmyrev** [comment]
请等到本周末更新

**Comment by nshmyrev** [comment]
可以下载中文模型。 还不准确。 我仍在对其进行优化。

**Comment by nshmyrev** [comment]
现在该模型已经足够好了。 让我知道事情的后续。
