### ISSUE TITLE
word lists for models for different languages

### ISSUE THREAD

**Issue by rickerteliane** [alphacep/kaldi-android-demo#21]
Is there a possibility to get the words.txt out of the provided models in the release section? or that you could upload it as well? (I'm interested in de words list for the alphacep-model-android-de-zamia-0.3.tar.gz)
Thanks in advance for your help!

**Comment by nshmyrev** [comment]
You can get the list like this:

`fstsymbols --save_osymbols=words.txt Gr.fst > /dev/null`

I will upload them later together with the tree files to allow model rebuild.

**Comment by rickerteliane** [comment]
thanks a lot for your help - I get the following errors:

ERROR: GenericRegister::GetEntry: ngram-fst.so: cannot open shared object file: No such file or directory
ERROR: Fst::Read: Unknown FST type ngram (arc type = standard): Gr.fst

is it possible that my fst-installation is broken?

**Comment by nshmyrev** [comment]
You need something like

export LD_LIBRARY_PATH=<full path>/kaldi/tools/openfst/lib/fst

and openfst has to be compiled with ngram and lookahead support.

**Comment by rickerteliane** [comment]
thank you so much, this did the trick!
