### ISSUE TITLE
Confusing licensing

### ISSUE THREAD

**Issue by smccants** [alphacep/kaldi-android-demo#22]
At the top level of this project, the COPYING file says the project is licensed under Apache 2.0, but KaldiActivity.java has a copyright notice that contradicts this.

KaldiActivity.java states:

>  * Copyright (c) 2019 Alpha Cephei Inc.  All rights reserved.

I'm assuming that the project is intended to be licensed under Apache 2.0, so this is a request to fix or remove the copyright notice in KaldiActivity.java.

**Comment by nshmyrev** [comment]
Updated, thank you for reporting, let me know if some other issue exists!

**Comment by smccants** [comment]
Thanks for fixing that so quickly!  And thank you for such a useful example!
