### ISSUE TITLE
自定义模型输入维度不匹配

### ISSUE THREAD

**Issue by orangetcy** [alphacep/kaldi-android-demo#23]
您好，我初学kaldi，发现这个项目可以很快速使用Android应用kaldi，跑通了项目的示例。可是我用自己的训练模型，我没有找到mkgraph_lookahead.sh，使用egs/wsj/s5/utils/mkgraph_lookahead.sh转换之后得到的final.mdl和HCLG文件，在使用时提示我输入不匹配，如 [此图](https://drive.google.com/open?id=1_ABcVb3ZUQNxJLsxbkUhkZI6yJDFWWbR)。后来我修改了mfcc中的配置num-mel-bins=16， 又提示我如 [此图](https://drive.google.com/open?id=1uMv-CYEPhCH6kLE1gg5Vud7S5WLWju9Y)， 请问我需要怎么解决呢或者您有什么推荐我使用的训练流程吗？谢谢

**Comment by nshmyrev** [comment]
> 可是我用自己的训练模型，我没有找到mkgraph_lookahead.sh，使用egs/wsj/s5/utils/mkgraph_lookahead.sh

你需要

`git clone -b lookahead --single-branch https://github.com/alphacep/kaldi`

脚本将在那里

> 又提示我如 此图

最后一个错误说您没有同步ivector / transform.mat。

**Comment by nshmyrev** [comment]
同样，我们不支持音高，请确保模型不使用音高。

**Comment by nshmyrev** [comment]
@orangetcy 结束这个问题好吗？
