### ISSUE TITLE
Create a model for different language

### ISSUE THREAD

**Issue by johnidm** [alphacep/kaldi-android-demo#25]
Is there any documentation on how to create additional language models?

I would like to work on a model for Brazilian Portuguese language.

**Comment by nshmyrev** [comment]
> Is there any documentation on how to create additional language models?

It is standard kaldi model training there are many materials around. You can start with http://kaldi-asr.org/doc/kaldi_for_dummies.html

> I would like to work on a model for Brazilian Portuguese language.

It will be released next week actually.

**Comment by johnidm** [comment]
@nshmyrev thanks for your prompt reply.

I will check out http://kaldi-asr.org/doc/kaldi_for_dummies.html

Good news about the upcoming release of a model for the Brazilian Portuguese language.

**Comment by nshmyrev** [comment]
Pt model released

https://github.com/alphacep/kaldi-android-demo/releases/download/2020-01/alphacep-model-android-pt-0.3.tar.gz

**Comment by Zunino** [comment]
I work with Johni and we'd both like to thank you for the prompt responses and for the pt-BR language model. We've been trying it out and getting good results (around 80% accuracy). Is there any way we could help you in enhancing that model? Thanks.

**Comment by nshmyrev** [comment]
Hello guys. I can give you the advise on better accuracy, sure, but I need to understand what system are you trying to build and ideally you'd better share sample recordings with me.

**Comment by Zunino** [comment]
Thank you, Nickolay. Would you mind if I shared the audio links with you via gmail? Cheers!

**Comment by nshmyrev** [comment]
Yes, you can contact me over gmail nshmyrev@gmail.com
