### ISSUE TITLE
Accuracy and Performance Enhancement

### ISSUE THREAD

**Issue by MuhammadRashid** [alphacep/kaldi-android-demo#26]
Hi Nickolay,

I have been using Kaldi Android from the past few months. I used your demo as a reference and a baseline. My requirement is continuous speech recognition to convert speech to a text from any audio source. On average, I am getting accuracy at 30 to 50% when I capture audio from the microphone. 

Can I increase accuracy to 90% and above?
Can you please guide me step by step to achieve that? 
Can you please elaborate on what extra steps I need to execute to get high accuracy?
Does Kaldi Android offer a paid SDK with high accuracy?

Can I get your personal/official email if possible?

**Comment by nshmyrev** [comment]
> Can I increase accuracy to 90% and above?

I'm not sure, depends on the task you are trying to solve.

> Can I get your personal/official email if possible?

nshmyrev@gmail.com

**Comment by nshmyrev** [comment]
After discussion for a best accuracy one better use a server recognizer, I've created #27 about it. Closing this one.
