### ISSUE TITLE
Demo app crashes in emulator

### ISSUE THREAD

**Issue by nikosapaster** [alphacep/kaldi-android-demo#30]
hello 
Following the instructions I have succesfully build the kaldi-android-demo to android studio.
When i try to open the kaldi demo app,the app crashes. I restarted it but it is still the same. Can someone know what can it be to cause this? Is it a machine problem of should I have to edit my code?

**Comment by nshmyrev** [comment]
Please provide the logcat output during the crash.

**Comment by nshmyrev** [comment]
And the information about your phone.

**Comment by nikosapaster** [comment]
i create with AVD manager an virtual phone Pixel 2 XL API 28.
The phone works fine, but the app stops everytime.
![Screenshot from 2020-02-12 14-52-10](https://user-images.githubusercontent.com/57747422/74336626-4e7e5200-4da7-11ea-9c9a-85202a07216e.png)

**Comment by nshmyrev** [comment]
Most likely your emulator is 32-bit, I suggest you to upgrade to 64-bit version

https://android-developers.googleblog.com/2019/06/moving-android-studio-and-android.html

**Comment by nikosapaster** [comment]
thanks..it succesfully runs. I want to ask you if i want to edit the existing files that you have from kaldi with my data from training that i have done...do it works as well? or do I have to build the KALDI API ?

**Comment by nshmyrev** [comment]
Ok, great!

If you just want to replace the model, you can update the files, thats it. It will work. You can also rebuild kaldi with your changes with gradle script in our vosk-api repo if needed.

**Comment by nikosapaster** [comment]
My audio is greek...whould I have a problem with that? becasuse the emulator when I put the files in crashes again

**Comment by nshmyrev** [comment]
> My audio is greek...whould I have a problem with that?

No, we might share a pretrained greek model a bit later if you like.

> becasuse the emulator when I put the files in crashes again

For the details of the crash read the logcat output, most likely you didn't arrange the required files properly.
