### ISSUE TITLE
error on emulator when creating new model 

### ISSUE THREAD

**Issue by nikosapaster** [alphacep/kaldi-android-demo#33]
words.txt
disambig_tid.int
final.mdl
G.fst
HCLG.fst
mfcc.conf
word_boundary.int
and ivector
final.dubm
final.ie
final.mat
global_cmvn.stats
online_cmvn.conf
splice.conf
I have these files...i have train an nnet3 chain type model and when I put on model android it crashes...but all the models that have released and i have put them  work fine...Maybe is it about G.fst and HCLG.fst? Or did i put some wrong files?

**Comment by nshmyrev** [comment]
You need to compile Gr.fst and HCLr.fst with lookahead. See 

https://github.com/kaldi-asr/kaldi/blob/master/egs/mini_librispeech/s5/local/lookahead/run_lookahead.sh

**Comment by nshmyrev** [comment]
@nikosapaster any success?

**Comment by nshmyrev** [comment]
Feel free to reopen if needed.
