### ISSUE TITLE
KaldiFatalError while loading other models

### ISSUE THREAD

**Issue by androidsparkling** [alphacep/kaldi-android-demo#34]
`D/!!!!: /storage/emulated/0/Android/data/org.kaldi.demo/files/sync
V/KaldiDemo: Cannot open config file: /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/ru/0.3/mfcc.conf
E/libc++abi: terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError`

`Timestamp: 2020-03-02 11:52:20+0530
pid: 3820, tid: 3859, name: AsyncTask #1  >>> org.kaldi.demo <<<
uid: 10157
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError'
    x0  0000000000000000  x1  0000000000000f13  x2  0000000000000006  x3  00000072f6ddc1e0
    x4  fefeff7197cad49d  x5  fefeff7197cad49d  x6  fefeff7197cad49d  x7  7f7f7f7fffffffff
    x8  00000000000000f0  x9  f66b9465304d9f32  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 7272456c61746146  x14 0000007298c6713c  x15 0000000000000000
    x16 0000007384b608c0  x17 0000007384b3c900  x18 000000729a9f8000  x19 0000000000000eec
    x20 0000000000000f13  x21 00000000ffffffff  x22 ffffff80ffffffc8  x23 00000072f6ddc430
    x24 00000072f6ddc310  x25 00000072f6ddc350  x26 00000072f6ddf020  x27 0000007298d91ca8
    x28 00000072f6ddcac8  x29 00000072f6ddc280
    sp  00000072f6ddc1c0  lr  0000007384aee0c4  pc  0000007384aee0f0`

Trying to load Russian model. But i am getting this FatalError, any idea ??

**Comment by nshmyrev** [comment]
Please provide the logcat lines above the issue.

**Comment by nshmyrev** [comment]
Any update? Feel free to reopen if needed.
