### ISSUE TITLE
The latency at beginning when the demo start to work is larger

### ISSUE THREAD

**Issue by huynguyen82** [alphacep/kaldi-android-demo#36]
Hi Nickolay,
I built a version for Android. Everything was fine but only one problem that the latency at first 2-3 seconds is larger. After starting the demo and speaking some words, having to wait for 2 or 3 seconds to get results on the screen. But after some words appear on screen then the demo is seem working in real time. Could i fix this?

**Comment by nshmyrev** [comment]
There is ivector initialization part which needs love. Maybe your ivector dimension is too large, I train models with ivector dim 30 instead of default 100.

**Comment by nshmyrev** [comment]
Let me know if smaller ivector helps. Feel free to reopen.
