### ISSUE TITLE
How to create our own data models, and application getting stoped in emulator?

### ISSUE THREAD

**Issue by hicrk2412** [alphacep/kaldi-android-demo#37]
![assests models](https://user-images.githubusercontent.com/51029436/76822028-cfcd6800-67dd-11ea-8cd6-1395f5ea6445.PNG)
 Help me to create new own assets...
and which software is used to open those file and get modify it...

**Comment by nshmyrev** [comment]
You can use Kaldi

https://kaldi-asr.org

**Comment by JeetSA** [comment]
Hello @hicrk2412 

Did you get any success for creating custom data models? Can you please help me with this?

Thanks
