### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by HuangChaoChao** [alphacep/kaldi-android-demo#4]
我是一名语音识别好爱者，看了您的项目，想follow，编译成功了，但是运行时卡在couldn't find "libkaldi_jni.so"，不知道这是怎么引起的，大神能抽空看看什么原因嘛

**Comment by nshmyrev** [comment]
您的手机架构是什么，是arm64吗？

**Comment by HuangChaoChao** [comment]
是的，libkaldi_jni.so 找不到，是把它放在jniLibs下面嘛

**Comment by nshmyrev** [comment]
我们现在仅支持32位，很快将计划使用64位。 您还可以检查https://medium.com/swlh/compile-kaldi-for-64-bit-android-on-ubuntu-18-70967eb3a308

**Comment by HuangChaoChao** [comment]
大神谢谢你，我手机架构确实是这样，如果我要改成64位的要修改哪里呢

**Comment by HuangChaoChao** [comment]
大神，我做了向下兼容，以前是首页进不去就退了，现在是在首页一段时间退了

**Comment by nshmyrev** [comment]
我已经更新了arm64，请再试一次。
