### ISSUE TITLE
Can i add new word to recognise into android kaldi demo model?

### ISSUE THREAD

**Issue by kamlesh-solution** [alphacep/kaldi-android-demo#43]
Hello,

I want to know that can i add new word and retrain existing kaldi android demo model ?https://github.com/alphacep/kaldi-android-demo/tree/master/models/src/main/assets/sync/model-android
and from where i can get dataset and source file of this existing trained kaldi android demo model?

Thanks.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/41

> from where i can get dataset and source file of this existing trained kaldi android demo model?

Overall, datasets are available on https://openslr.org. You can contact us in private about source files.
