### ISSUE TITLE
Fatal Error When Using Different Model

### ISSUE THREAD

**Issue by ammyt** [alphacep/kaldi-android-demo#52]
Hi,
I have been trying to use the tdnn_f German model from https://goofy.zamia.org/asr/.

I copied the respective files from the tar according to https://github.com/alphacep/vosk-server/blob/master/docker/Dockerfile.kaldi-de. The app launches but as soon as I want to initiate recognizing (either via microphone or file) I get a crash.

This is console output:
`E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/Assets: Copying asset model-android/ivector/final.dubm to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/final.dubm
I/Assets: Copying asset model-android/ivector/splice.conf to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/splice.conf
I/Assets: Copying asset model-android/ivector/final.mat to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/final.mat
I/Assets: Copying asset model-android/mfcc.conf to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/mfcc.conf
I/Assets: Copying asset model-android/words.txt to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/words.txt
I/Assets: Copying asset model-android/word_boundary.int to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/word_boundary.int
I/Assets: Copying asset model-android/ivector/global_cmvn.stats to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/global_cmvn.stats
I/Assets: Copying asset model-android/ivector/online_cmvn.conf to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/online_cmvn.conf
I/Assets: Copying asset model-android/mfcc_hires.conf to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/mfcc_hires.conf
I/Assets: Copying asset model-android/ivector/final.ie to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/final.ie
I/org.kaldi.demo: ProcessProfilingInfo new_methods=26 is saved saved_to_disk=1 resolve_classes_delay=8000
I/Assets: Copying asset model-android/HCLG.fst to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/HCLG.fst
I/Assets: Copying asset model-android/final.mdl to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/final.mdl
D/!!!!: /storage/emulated/0/Android/data/org.kaldi.demo/files/sync
V/KaldiDemo: Computing derived variables for iVector extractor
V/KaldiDemo: Done.
V/KaldiDemo: Removed 1 orphan nodes.
    Removing 2 orphan components.
    Added 1 components, removed 2
V/KaldiDemo: Spent 0.0701852 seconds in looped compilation.
V/KaldiDemo: Dimension mismatch: source features have dimension 91 and LDA #cols is 280
E/libc++abi: terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 24275 (AsyncTask #2), pid 23206 (org.kaldi.demo)`

Full logcat attached. Any help is appreciated!
[logcat.txt](https://github.com/alphacep/kaldi-android-demo/files/4554556/logcat.txt)

**Comment by nshmyrev** [comment]
You should have take mfcc_hires.conf, you mistakenly tool mfcc.conf.

Use our model, it is properly repackaged zamia:

https://github.com/alphacep/kaldi-android-demo/releases/download/2020-01/alphacep-model-android-de-zamia-0.3.tar.gz
