### ISSUE TITLE
SpeechRecognizer defined word list

### ISSUE THREAD

**Issue by akrueger90** [alphacep/kaldi-android-demo#55]
Hello, 

is it possible to give the SpeechRecognizer a specific word list. I already built my own model which is working. But I would like to further reduce the recognizable words dynamically based on the context. 

Kind regards

**Comment by nshmyrev** [comment]
https://github.com/alphacep/kaldi-android-demo/blob/a52ae0fc8fd5be6e8bb21d6e2b8fa8f30fde907a/app/src/main/java/org/kaldi/demo/KaldiActivity.java#L147

**Comment by akrueger90** [comment]
If I understand correct the KaldiRecognizer in this case is used for the file word recognition. For the microphone I would need this parameter for the SpeechRecognizer I guess.

**Comment by nshmyrev** [comment]
Feel free to submit a pull request

**Comment by abouquet** [comment]
Is it related with https://github.com/alphacep/kaldi-android-demo/issues/18 ?

**Comment by abouquet** [comment]
> If I understand correct the KaldiRecognizer in this case is used for the file word recognition. For the microphone I would need this parameter for the SpeechRecognizer I guess.

It seems, it's relativly easy to do it.

There is already an existing constructor on the JNI side

```
    public KaldiRecognizer(Model model, float sample_frequency, String grammar) {
        this(voskJNI.new_KaldiRecognizer__SWIG_2(Model.getCPtr(model), model, sample_frequency, grammar), true);
    }
```

We just have to declare an other one for `KaldiRecognizer` class.

I can maybe try to do this PR.
