### ISSUE TITLE
"Preparing the recognizer" never ends

### ISSUE THREAD

**Issue by gklasen** [alphacep/kaldi-android-demo#9]
Hey there,

first, thanks for the work. Unfortunately, I can not get past this error, which prevents the usage:

2019-11-29 11:02:41.878 9779-9796/org.kaldi.demo V/KaldiDemo: Could not read symbol table from file /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/words.txt

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/kaldi-android-demo/issues/8 ? Which version do you try?

**Comment by gklasen** [comment]
Looks very similar yes. I just cloned (~ 10 Minutes ago)

**Comment by nshmyrev** [comment]
Please check CR+LF in words.txt file

**Comment by gklasen** [comment]
Sorry, can you clarify?

**Comment by gklasen** [comment]
CR+LF was replaced by CR only, now working.

**Comment by nshmyrev** [comment]
Ok, looks good then, same as #8

**Comment by gklasen** [comment]
Maybe nice addition: I can work with both endings (CR only / LF only). But only get results delivered back with LF. CR only is causing empty results.
